load(
      "@rules_cc//cc:defs.bzl"
   ,  "cc_library"
)

cc_library(
      name       = "aapFunctionalCluster_RawDataStream"
   ,  srcs       = ["aapFunctionalCluster_RawDataStream.cpp"]
#  ,  deps       = ["//repo_projects/pProjectFull/main_LATEST/source/SwcServiceEcuM:SwcServiceEcuM"]
   ,  hdrs       = [
            "interface_RawDataStream_RawDataStreamClient.hpp"
         ,  "interface_RawDataStream_RawDataStreamServer.hpp"
      ]
   ,  includes   = ["."]
   ,  visibility = ["//visibility:public"]
)

